### ISSUE TITLE
Too much jitter on newer versions of vort_TAA.fhx

### ISSUE THREAD

**Issue by xHybred** [vortigern11/vort_Shaders#1]
The screen just jitters/shakes too much on newer versions and its distracting, the older version I downloaded and am using doesn't do this and looks much better, I uploaded it so you know which version I'm talking about and can test it yourself: https://www.mediafire.com/file/56ptlfjmdgs5fu5/vort_TAA.fxh/file

I highly recommend reverting the change or giving us control over the jitter, its so bad in the newer ones. Thanks for reading

**Comment by vortigern11** [comment]
Control over the jitter was always there. Currently it is called `TAA Static AA` under the `Motion Effects` category in the UI.
Even though I didn't notice the issue you are describing, I reverted the jitter changes.
Just download the latest version - commit `a3e7589` .

**Comment by xHybred** [comment]
> Control over the jitter was always there. Currently it is called `TAA Static AA` under the `Motion Effects` category in the UI. Even though I didn't notice the issue you are describing, I reverted the jitter changes. Just download the latest version - commit `a3e7589` .

Well in the older version when using Static TAA at 100%, I didn't notice any jittering but in the newer versions it was there.

The reason I used it at its max value was because I didn't want their to be sudden clarity differences between stationary and motion, so making the stationary image match the clarity of how the TAA looked in motion helped with my motion sickness, & allows sharpness to be applied consistently since its only accounting for one level of clarity even if the stationary image is blurrier.

Which seemed to be impossible to do with your new jitter. 

Thank you for the quick response
