### ISSUE TITLE
Can't compile vort_MotionBlur.fx

### ISSUE THREAD

**Issue by U3b3** [vortigern11/vort_Shaders#2]
Running Reshade 6.0.1

![grafik](https://github.com/vortigern11/vort_Shaders/assets/68308468/a0a31403-554e-4664-9d0b-f384d29f1867)

![grafik](https://github.com/vortigern11/vort_Shaders/assets/68308468/61f1e44b-9e11-4a58-b71c-ba7e30d7656f)

With 6.0.0 it was working , but i've installed a new Windows today and now i got this compile error

Any Help ?

**Comment by U3b3** [comment]
![grafik](https://github.com/vortigern11/vort_Shaders/assets/68308468/91443f53-9c7f-4526-ab2e-1be20ec8ae02)

im using vort_Motion now , motion blur works now.

**Comment by vortigern11** [comment]
vort_MotionBlur doesn't exist for some time now.
It has been superseded by vort_Motion.
I'm closing this since it is not an actual issue, you just had leftover files from previous version.
