### ISSUE TITLE
Warping effect in some games (i.e STALKER 2) with Vort TAA

### ISSUE THREAD

**Issue by xHybred** [vortigern11/vort_Shaders#5]
https://streamable.com/3l7i9s

Idk why it doesn't happen in every game. Even when making the frame blending light it still does it. I updated to the latest version, it still happens

**Comment by vortigern11** [comment]
Not interested in changing my TAA further, unless a major breakthrough happens.
Every TAA solution in ReShade is not working correctly, so you should search for another solution (like SMAA).
